"""
Quick Modern TTS Sample Generator
Generate 500-1000 fake voice samples using free TTS systems
Time: ~1-2 hours
"""

import os
import random
from pathlib import Path

# Install required packages first:
# pip install gTTS pyttsx3 edge-tts

def generate_samples_gtts(output_dir, num_samples=200):
    """Generate samples using Google TTS (Free)"""
    from gtts import gTTS
    
    texts = [
        "Hello, this is a test of the deepfake detection system.",
        "The weather today is quite pleasant and sunny.",
        "I am calling to inform you about an important update.",
        "Please verify your account information immediately.",
        "This is an automated message from your bank.",
        # Add more varied texts
    ]
    
    languages = ['en', 'en-us', 'en-uk', 'en-au']
    
    print(f"Generating {num_samples} samples with Google TTS...")
    for i in range(num_samples):
        text = random.choice(texts)
        lang = random.choice(languages)
        
        try:
            tts = gTTS(text=text, lang=lang, slow=False)
            output_file = os.path.join(output_dir, f'gtts_fake_{i}.mp3')
            tts.save(output_file)
            
            if (i + 1) % 50 == 0:
                print(f"  Generated {i + 1}/{num_samples} samples")
        except Exception as e:
            print(f"  Error on sample {i}: {e}")
            continue
    
    print(f"✓ Google TTS: Generated {num_samples} samples")

def generate_samples_pyttsx3(output_dir, num_samples=200):
    """Generate samples using pyttsx3 (Offline, Free)"""
    import pyttsx3
    
    texts = [
        "This is a synthetic voice generated by text to speech.",
        "Your package has been delivered to your address.",
        "Please call back at your earliest convenience.",
        "We have an important security alert for your account.",
        "Thank you for using our automated service.",
    ]
    
    print(f"Generating {num_samples} samples with pyttsx3...")
    engine = pyttsx3.init()
    
    # Try different voices
    voices = engine.getProperty('voices')
    
    for i in range(num_samples):
        text = random.choice(texts)
        voice = random.choice(voices)
        
        try:
            engine.setProperty('voice', voice.id)
            engine.setProperty('rate', random.randint(150, 200))
            
            output_file = os.path.join(output_dir, f'pyttsx3_fake_{i}.wav')
            engine.save_to_file(text, output_file)
            engine.runAndWait()
            
            if (i + 1) % 50 == 0:
                print(f"  Generated {i + 1}/{num_samples} samples")
        except Exception as e:
            print(f"  Error on sample {i}: {e}")
            continue
    
    print(f"✓ pyttsx3: Generated {num_samples} samples")

async def generate_samples_edge_tts(output_dir, num_samples=300):
    """Generate samples using Edge TTS (Free, High Quality)"""
    import edge_tts
    import asyncio
    
    texts = [
        "This is a test message for voice authentication.",
        "Your verification code is five seven three two.",
        "Please confirm your identity before proceeding.",
        "We detected unusual activity on your account.",
        "This call may be recorded for quality assurance.",
    ]
    
    voices = [
        "en-US-AriaNeural",
        "en-US-GuyNeural",
        "en-US-JennyNeural",
        "en-GB-SoniaNeural",
        "en-AU-NatashaNeural",
    ]
    
    print(f"Generating {num_samples} samples with Edge TTS...")
    for i in range(num_samples):
        text = random.choice(texts)
        voice = random.choice(voices)
        
        try:
            output_file = os.path.join(output_dir, f'edge_tts_fake_{i}.mp3')
            communicate = edge_tts.Communicate(text, voice)
            await communicate.save(output_file)
            
            if (i + 1) % 50 == 0:
                print(f"  Generated {i + 1}/{num_samples} samples")
        except Exception as e:
            print(f"  Error on sample {i}: {e}")
            continue
    
    print(f"✓ Edge TTS: Generated {num_samples} samples")

def main():
    """Generate 700 fake samples using free TTS systems"""
    
    output_dir = "data/fake_generated"
    os.makedirs(output_dir, exist_ok=True)
    
    print("\n" + "="*60)
    print("GENERATING MODERN TTS SAMPLES")
    print("="*60)
    print(f"Output directory: {output_dir}")
    print(f"Target: 700 samples")
    print(f"Estimated time: 1-2 hours")
    print("="*60 + "\n")
    
    # Generate with different TTS systems
    generate_samples_gtts(output_dir, num_samples=200)
    generate_samples_pyttsx3(output_dir, num_samples=200)
    
    # Edge TTS (async)
    import asyncio
    asyncio.run(generate_samples_edge_tts(output_dir, num_samples=300))
    
    print("\n" + "="*60)
    print("✓ GENERATION COMPLETE!")
    print("="*60)
    print(f"Total samples generated: ~700")
    print(f"Location: {output_dir}")
    print("\nNext step: Convert to WAV and move to data/fake/")
    print("="*60)

if __name__ == "__main__":
    main()
